//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiomasaEUPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradas
    {
        public int id_entrada { get; set; }
        public System.DateTime fecha_recepcion { get; set; }
        public int mes { get; set; }
        public int ano { get; set; }
        public string numero_albaran { get; set; }
    }
}
