//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiomasaEUPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class envasados
    {
        public int id_envasado { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public double peso { get; set; }
        public double volumen { get; set; }
        public Nullable<int> unidades { get; set; }
        public string codigo { get; set; }
    }
}
