//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiomasaEUPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class materias_primas
    {
        public int id_materia_prima { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public int tipo_id { get; set; }
        public int grupo_id { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> volumen { get; set; }
        public Nullable<int> unidades { get; set; }
        public int entrada_id { get; set; }
        public int sitio_id { get; set; }
        public int proveedor_id { get; set; }
        public int procedencia_id { get; set; }
        public string codigo { get; set; }
    
        public virtual grupos_materias_primas grupos_materias_primas { get; set; }
        public virtual procedencias procedencias { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual sitios_descargas sitios_descargas { get; set; }
        public virtual tipos_materias_primas tipos_materias_primas { get; set; }
    }
}
