//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiomasaEUPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedores()
        {
            this.materias_primas = new HashSet<materias_primas>();
        }
    
        public int id_proveedor { get; set; }
        public string razon_social { get; set; }
        public string nif { get; set; }
        public string email { get; set; }
        public string calle { get; set; }
        public string observaciones { get; set; }
        public int tipo_id { get; set; }
        public int direccion_id { get; set; }
    
        public virtual direcciones direcciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materias_primas> materias_primas { get; set; }
        public virtual tipos_proveedores tipos_proveedores { get; set; }
    }
}
