//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiomasaEUPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitios_descargas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sitios_descargas()
        {
            this.materias_primas = new HashSet<materias_primas>();
        }
    
        public int id_sitio_descarga { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> volumen { get; set; }
        public Nullable<int> unidades { get; set; }
        public int tipo_materia_id { get; set; }
        public string tipo_materia_nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materias_primas> materias_primas { get; set; }
    }
}
