//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiomasaEUPT
{
    using System;
    using System.Collections.Generic;
    
    public partial class vista_materias_primas
    {
        public int id_materia_prima { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public int tipo_id { get; set; }
        public string tipo_nombre { get; set; }
        public int grupo_id { get; set; }
        public string grupo_nombre { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> volumen { get; set; }
        public Nullable<int> unidades { get; set; }
        public int entrada_id { get; set; }
        public int sitio_id { get; set; }
        public string sitio_nombre { get; set; }
        public int proveedor_id { get; set; }
        public string proveedor_razon_social { get; set; }
        public int procedencia_id { get; set; }
        public string procedencia_nombre { get; set; }
        public string codigo { get; set; }
    }
}
